Loading modules...
Running test...
INFO 08-25 13:35:48 [__init__.py:241] Automatically detected platform cuda.
INFO 08-25 13:35:50 [utils.py:326] non-default args: {'model': 'unsloth/phi-4-unsloth-bnb-4bit', 'download_dir': '/src/extract_pipeline/models', 'disable_log_stats': True}
INFO 08-25 13:36:02 [__init__.py:711] Resolved architecture: LlamaForCausalLM
INFO 08-25 13:36:02 [__init__.py:1750] Using max model len 16384
WARNING 08-25 13:36:03 [__init__.py:1171] bitsandbytes quantization is not fully optimized yet. The speed can be slower than non-quantized models.
INFO 08-25 13:36:04 [scheduler.py:222] Chunked prefill is enabled with max_num_batched_tokens=8192.
[1;36m(EngineCore_0 pid=5009)[0;0m INFO 08-25 13:36:04 [core.py:636] Waiting for init message from front-end.
[1;36m(EngineCore_0 pid=5009)[0;0m INFO 08-25 13:36:04 [core.py:74] Initializing a V1 LLM engine (v0.10.1.1) with config: model='unsloth/phi-4-unsloth-bnb-4bit', speculative_config=None, tokenizer='unsloth/phi-4-unsloth-bnb-4bit', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=16384, download_dir='/src/extract_pipeline/models', load_format=bitsandbytes, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=bitsandbytes, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=unsloth/phi-4-unsloth-bnb-4bit, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":1,"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{},"max_capture_size":512,"local_cache_dir":null}
[1;36m(EngineCore_0 pid=5009)[0;0m INFO 08-25 13:36:06 [parallel_state.py:1134] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
[1;36m(EngineCore_0 pid=5009)[0;0m WARNING 08-25 13:36:06 [topk_topp_sampler.py:61] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
[1;36m(EngineCore_0 pid=5009)[0;0m INFO 08-25 13:36:06 [gpu_model_runner.py:1953] Starting to load model unsloth/phi-4-unsloth-bnb-4bit...
[1;36m(EngineCore_0 pid=5009)[0;0m INFO 08-25 13:36:06 [gpu_model_runner.py:1985] Loading model from scratch...
[1;36m(EngineCore_0 pid=5009)[0;0m INFO 08-25 13:36:13 [cuda.py:328] Using Flash Attention backend on V1 engine.
[1;36m(EngineCore_0 pid=5009)[0;0m INFO 08-25 13:36:14 [bitsandbytes_loader.py:742] Loading weights with BitsAndBytes quantization. May take a while ...
[1;36m(EngineCore_0 pid=5009)[0;0m INFO 08-25 13:36:14 [weight_utils.py:296] Using model weights format ['*.safetensors']
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700] EngineCore failed to start.
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700] Traceback (most recent call last):
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 691, in run_engine_core
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 492, in __init__
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 80, in __init__
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]     self.model_executor = executor_class(vllm_config)
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/executor/executor_base.py", line 54, in __init__
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]     self._init_executor()
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/executor/uniproc_executor.py", line 49, in _init_executor
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]     self.collective_rpc("load_model")
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/executor/uniproc_executor.py", line 58, in collective_rpc
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]     answer = run_method(self.driver_worker, method, args, kwargs)
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/utils/__init__.py", line 3007, in run_method
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/worker/gpu_worker.py", line 212, in load_model
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]     self.model_runner.load_model(eep_scale_up=eep_scale_up)
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/worker/gpu_model_runner.py", line 1986, in load_model
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]     self.model = model_loader.load_model(
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]                  ^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/model_executor/model_loader/base_loader.py", line 49, in load_model
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]     self.load_weights(model, model_config)
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/model_executor/model_loader/bitsandbytes_loader.py", line 745, in load_weights
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]     self._get_quantized_weights_iterator(
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/model_executor/model_loader/bitsandbytes_loader.py", line 206, in _get_quantized_weights_iterator
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]     hf_weights_files, use_safetensors = self._prepare_weights(
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]                                         ^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/model_executor/model_loader/bitsandbytes_loader.py", line 122, in _prepare_weights
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]     hf_folder, hf_weights_files, matched_pattern = self._get_weight_files(
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]                                                    ^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/model_executor/model_loader/bitsandbytes_loader.py", line 103, in _get_weight_files
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]     hf_folder = download_weights_from_hf(
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]                 ^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/model_executor/model_loader/weight_utils.py", line 299, in download_weights_from_hf
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]     with get_lock(model_name_or_path, cache_dir):
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/model_executor/model_loader/weight_utils.py", line 89, in get_lock
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]     os.makedirs(os.path.dirname(lock_dir), exist_ok=True)
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]   File "<frozen os>", line 215, in makedirs
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700]   File "<frozen os>", line 225, in makedirs
[1;36m(EngineCore_0 pid=5009)[0;0m ERROR 08-25 13:36:14 [core.py:700] PermissionError: [Errno 13] Permission denied: '/src'
[1;36m(EngineCore_0 pid=5009)[0;0m Process EngineCore_0:
[1;36m(EngineCore_0 pid=5009)[0;0m Traceback (most recent call last):
[1;36m(EngineCore_0 pid=5009)[0;0m   File "/software/eb/Python/3.11.5-GCCcore-13.2.0/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
[1;36m(EngineCore_0 pid=5009)[0;0m     self.run()
[1;36m(EngineCore_0 pid=5009)[0;0m   File "/software/eb/Python/3.11.5-GCCcore-13.2.0/lib/python3.11/multiprocessing/process.py", line 108, in run
[1;36m(EngineCore_0 pid=5009)[0;0m     self._target(*self._args, **self._kwargs)
[1;36m(EngineCore_0 pid=5009)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 704, in run_engine_core
[1;36m(EngineCore_0 pid=5009)[0;0m     raise e
[1;36m(EngineCore_0 pid=5009)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 691, in run_engine_core
[1;36m(EngineCore_0 pid=5009)[0;0m     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_0 pid=5009)[0;0m                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=5009)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 492, in __init__
[1;36m(EngineCore_0 pid=5009)[0;0m     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_0 pid=5009)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 80, in __init__
[1;36m(EngineCore_0 pid=5009)[0;0m     self.model_executor = executor_class(vllm_config)
[1;36m(EngineCore_0 pid=5009)[0;0m                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=5009)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/executor/executor_base.py", line 54, in __init__
[1;36m(EngineCore_0 pid=5009)[0;0m     self._init_executor()
[1;36m(EngineCore_0 pid=5009)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/executor/uniproc_executor.py", line 49, in _init_executor
[1;36m(EngineCore_0 pid=5009)[0;0m     self.collective_rpc("load_model")
[1;36m(EngineCore_0 pid=5009)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/executor/uniproc_executor.py", line 58, in collective_rpc
[1;36m(EngineCore_0 pid=5009)[0;0m     answer = run_method(self.driver_worker, method, args, kwargs)
[1;36m(EngineCore_0 pid=5009)[0;0m              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=5009)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/utils/__init__.py", line 3007, in run_method
[1;36m(EngineCore_0 pid=5009)[0;0m     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=5009)[0;0m            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=5009)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/worker/gpu_worker.py", line 212, in load_model
[1;36m(EngineCore_0 pid=5009)[0;0m     self.model_runner.load_model(eep_scale_up=eep_scale_up)
[1;36m(EngineCore_0 pid=5009)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/worker/gpu_model_runner.py", line 1986, in load_model
[1;36m(EngineCore_0 pid=5009)[0;0m     self.model = model_loader.load_model(
[1;36m(EngineCore_0 pid=5009)[0;0m                  ^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=5009)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/model_executor/model_loader/base_loader.py", line 49, in load_model
[1;36m(EngineCore_0 pid=5009)[0;0m     self.load_weights(model, model_config)
[1;36m(EngineCore_0 pid=5009)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/model_executor/model_loader/bitsandbytes_loader.py", line 745, in load_weights
[1;36m(EngineCore_0 pid=5009)[0;0m     self._get_quantized_weights_iterator(
[1;36m(EngineCore_0 pid=5009)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/model_executor/model_loader/bitsandbytes_loader.py", line 206, in _get_quantized_weights_iterator
[1;36m(EngineCore_0 pid=5009)[0;0m     hf_weights_files, use_safetensors = self._prepare_weights(
[1;36m(EngineCore_0 pid=5009)[0;0m                                         ^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=5009)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/model_executor/model_loader/bitsandbytes_loader.py", line 122, in _prepare_weights
[1;36m(EngineCore_0 pid=5009)[0;0m     hf_folder, hf_weights_files, matched_pattern = self._get_weight_files(
[1;36m(EngineCore_0 pid=5009)[0;0m                                                    ^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=5009)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/model_executor/model_loader/bitsandbytes_loader.py", line 103, in _get_weight_files
[1;36m(EngineCore_0 pid=5009)[0;0m     hf_folder = download_weights_from_hf(
[1;36m(EngineCore_0 pid=5009)[0;0m                 ^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=5009)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/model_executor/model_loader/weight_utils.py", line 299, in download_weights_from_hf
[1;36m(EngineCore_0 pid=5009)[0;0m     with get_lock(model_name_or_path, cache_dir):
[1;36m(EngineCore_0 pid=5009)[0;0m          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=5009)[0;0m   File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/model_executor/model_loader/weight_utils.py", line 89, in get_lock
[1;36m(EngineCore_0 pid=5009)[0;0m     os.makedirs(os.path.dirname(lock_dir), exist_ok=True)
[1;36m(EngineCore_0 pid=5009)[0;0m   File "<frozen os>", line 215, in makedirs
[1;36m(EngineCore_0 pid=5009)[0;0m   File "<frozen os>", line 225, in makedirs
[1;36m(EngineCore_0 pid=5009)[0;0m PermissionError: [Errno 13] Permission denied: '/src'
Traceback (most recent call last):
  File "/lustre/romanistik/leonnial/gec_extractor/./src/extract_pipeline/test.py", line 28, in <module>
    main()
  File "/lustre/romanistik/leonnial/gec_extractor/./src/extract_pipeline/test.py", line 14, in main
    llm = LLM(model="unsloth/phi-4-unsloth-bnb-4bit",
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/entrypoints/llm.py", line 285, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 490, in from_engine_args
    return engine_cls.from_vllm_config(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/llm_engine.py", line 127, in from_vllm_config
    return cls(vllm_config=vllm_config,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/llm_engine.py", line 104, in __init__
    self.engine_core = EngineCoreClient.make_client(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/core_client.py", line 80, in make_client
    return SyncMPClient(vllm_config, executor_class, log_stats)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/core_client.py", line 600, in __init__
    super().__init__(
  File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/core_client.py", line 446, in __init__
    with launch_core_engines(vllm_config, executor_class,
  File "/software/eb/Python/3.11.5-GCCcore-13.2.0/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/utils.py", line 706, in launch_core_engines
    wait_for_engine_startup(
  File "/lustre/romanistik/leonnial/gec_extractor/venv/run_hpc/lib/python3.11/site-packages/vllm/v1/engine/utils.py", line 759, in wait_for_engine_startup
    raise RuntimeError("Engine core initialization failed. "
RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}
Script finished!
